"""Add added date to review

Revision ID: 02161c3076d3
Revises: 2c4097b27c85
Create Date: 2025-11-07 15:21:57.797736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02161c3076d3'
down_revision: Union[str, Sequence[str], None] = '2c4097b27c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('added_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'added_date')
    # ### end Alembic commands ###
