"""Remove user profile entity, move all those fields to user

Revision ID: 11ba386d762e
Revises: 
Create Date: 2025-11-02 14:11:34.635013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ba386d762e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('role', sa.String(), server_default=sa.text("'USER'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('blocked_for', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('author_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), server_default=sa.text('0.0'), nullable=True),
    sa.Column('common_genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('books_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('reviews_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('likes_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('cover_path', sa.String(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('added_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'ON_MODERATE'"), nullable=False),
    sa.Column('total_rating', sa.Float(), server_default=sa.text('0.0'), nullable=True),
    sa.Column('likes_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('pages_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('reviews_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_likes',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'user_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_book_statuses',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'user_id')
    )
    op.create_table('review_likes',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('review_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_likes')
    op.drop_table('user_book_statuses')
    op.drop_table('reviews')
    op.drop_table('book_likes')
    op.drop_table('books')
    op.drop_table('author_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
