"""Add some new fields to models

Revision ID: 21f3fa4ffdcf
Revises: 71eff4a26a8b
Create Date: 2025-10-22 11:05:51.764439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f3fa4ffdcf'
down_revision: Union[str, Sequence[str], None] = '71eff4a26a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_profiles', sa.Column('books_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('author_profiles', sa.Column('reviews_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('author_profiles', sa.Column('likes_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('author_profiles', sa.Column('status', sa.String(), server_default=sa.text("'ACTIVE'"), nullable=False))
    op.add_column('books', sa.Column('added_date', sa.Date(), nullable=True))
    op.add_column('books', sa.Column('total_rating', sa.Float(), server_default=sa.text('0.0'), nullable=True))
    op.add_column('books', sa.Column('likes_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('books', sa.Column('pages_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('books', sa.Column('reviews_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.drop_column('books', 'issued_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('issued_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('books', 'reviews_count')
    op.drop_column('books', 'pages_count')
    op.drop_column('books', 'likes_count')
    op.drop_column('books', 'total_rating')
    op.drop_column('books', 'added_date')
    op.drop_column('author_profiles', 'status')
    op.drop_column('author_profiles', 'likes_count')
    op.drop_column('author_profiles', 'reviews_count')
    op.drop_column('author_profiles', 'books_count')
    # ### end Alembic commands ###
