"""Add unique on user id in review, add user_name field in review

Revision ID: 2c4097b27c85
Revises: 11ba386d762e
Create Date: 2025-11-07 15:12:23.349096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4097b27c85'
down_revision: Union[str, Sequence[str], None] = '11ba386d762e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'reviews', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_column('reviews', 'user_name')
    # ### end Alembic commands ###
