"""Added cover file path to book entity

Revision ID: 340a3a62d25c
Revises: 4d98dff7621b
Create Date: 2025-10-24 21:34:06.311823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340a3a62d25c'
down_revision: Union[str, Sequence[str], None] = '4d98dff7621b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'cover_path')
    # ### end Alembic commands ###
