"""Add field for user blocking time

Revision ID: 4034d2f9e195
Revises: a362d155ce50
Create Date: 2025-10-29 22:43:27.732958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4034d2f9e195'
down_revision: Union[str, Sequence[str], None] = 'a362d155ce50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocked_for', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked_for')
    # ### end Alembic commands ###
