"""Remove unqiue constrait from review.user_id

Revision ID: 78ff73355714
Revises: f3a5543e69c2
Create Date: 2025-11-10 10:53:11.355753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ff73355714'
down_revision: Union[str, Sequence[str], None] = 'f3a5543e69c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reviews_user_id_key'), 'reviews', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('reviews_user_id_key'), 'reviews', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
