"""Remove login field and leave only username field (1 part)

Revision ID: c9076e1ecea0
Revises: 4034d2f9e195
Create Date: 2025-10-29 22:57:33.199336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9076e1ecea0'
down_revision: Union[str, Sequence[str], None] = '4034d2f9e195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('user_profiles', 'name')
    op.drop_constraint(op.f('users_login_key'), 'users', type_='unique')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_login_key'), 'users', ['login'], postgresql_nulls_not_distinct=False)
    op.add_column('user_profiles', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_profiles', 'username')
    # ### end Alembic commands ###
