"""Add end page in book status

Revision ID: f3a5543e69c2
Revises: fc1343be8fba
Create Date: 2025-11-08 19:49:22.997928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a5543e69c2'
down_revision: Union[str, Sequence[str], None] = 'fc1343be8fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_book_statuses', sa.Column('end_page', sa.Integer(), server_default=sa.text('-1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_book_statuses', 'end_page')
    # ### end Alembic commands ###
