"""Add added field to book status

Revision ID: fc1343be8fba
Revises: 7b1e32e6f7fa
Create Date: 2025-11-08 19:32:34.753618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1343be8fba'
down_revision: Union[str, Sequence[str], None] = '7b1e32e6f7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_book_statuses', sa.Column('added_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_book_statuses', 'added_date')
    # ### end Alembic commands ###
